### PR TITLE
Limit Mockserver memory usage

### PR DESCRIPTION
**Pull request by pehala**
This time it actually works (at least so far)

### CODE REVIEW

**Review by mdujava — APPROVED** [review]

**Comment by mganisin** [comment]
@pehala are you sure? I know you are :-) anyway brief reasoning why or if  this will avoid out of memory tracebacks would be nice.
Anyway we need this with no doubt maybe even lower quota

**Comment by pehala** [comment]
I think it works because the JVM tries to allocate a maximum percentage of available memory.

**Comment by mganisin** [comment]
> I think it works because the JVM tries to allocate a maximum percentage of available memory.

Could I ask you to put this assumtion to commit message?

**Comment by pehala** [comment]
> > I think it works because the JVM tries to allocate a maximum percentage of available memory.
> 
> Could I ask you to put this assumtion to commit message?

Done

**Review by mganisin — APPROVED** [review]

**Review by mdujava — APPROVED** [review]

**Pull request merged**
